---
title: "Factor Analysis"
author: "Deviprasad Saka"
date: "2024-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
```


```{r}


# Factor Analysis

library(psych)

ship <- read.csv("D:/Multivariate Analysis/Assignment-6/Ship_data.csv")

```

```{r}
summary(ship)
```

```{r}
fit.pc <- principal(ship, nfactors=4, rotate="varimax")
fit.pc
```

```{r}
round(fit.pc$values, 3)
fit.pc$loadings
```

```{r}
# Loadings with more digits
for (i in c(1,3,2,4)) { print(fit.pc$loadings[[1,i]])}
# Communalities
fit.pc$communality
```

```{r}

# Display the first 10 rows of the rotated factor scores with column ordering: RC1, RC3, RC2, and RC4
head(fit.pc$scores, 10)

```


```{r}
# Play with FA utilities

fa.parallel(ship) # See factor recommendation
```

```{r}
fa.plot(fit.pc) # See Correlations within Factors
```

```{r}
fa.diagram(fit.pc) # Visualize the relationship
```

```{r}
vss(ship) # See Factor recommendations for a simple structure
```


```{r}
# Computing Correlation Matrix
corrm.emp <- cor(ship)
corrm.emp
```

```{r}
plot(corrm.emp)
```

```{r}
ship_pca <- prcomp(ship, scale=TRUE)
summary(ship_pca)
```

```{r}
plot(ship_pca)
```


```{r}
# A table containing eigenvalues and %'s accounted, follows. Eigenvalues are the sdev^2
(eigen_ship <- round(ship_pca$sdev^2,3))
round(fit.pc$values, 3)
names(eigen_ship) <- paste("PC",1:9,sep="")
eigen_ship
```

```{r}
sumlambdas <- sum(eigen_ship)
sumlambdas
```

```{r}
propvar <- round(eigen_ship/sumlambdas,2)
propvar
```

```{r}
cumvar_ship <- cumsum(propvar)
cumvar_ship
```

```{r}
matlambdas <- rbind(eigen_ship,propvar,cumvar_ship)
matlambdas
```

```{r}
rownames(matlambdas) <- c("Eigenvalues","Prop. variance","Cum. prop. variance")
rownames(matlambdas)
```

```{r}
eigvec.emp <- ship_pca$rotation
print(ship_pca)
```

```{r}
# Taking the first four PCs to generate linear combinations for all the variables with four factors
pcafactors.emp <- eigvec.emp[,1:4]
pcafactors.emp
```

```{r}
# Multiplying each column of the eigenvector’s matrix by the square-root of the corresponding eigenvalue in order to get the factor loadings
unrot.fact.emp <- sweep(pcafactors.emp,MARGIN=2,ship_pca$sdev[1:4],`*`)
unrot.fact.emp
```

```{r}
# Computing communalities
communalities.emp <- rowSums(unrot.fact.emp^2)
communalities.emp
```

```{r}
# Performing the varimax rotation. The default in the varimax function is norm=TRUE thus, Kaiser normalization is carried out
rot.fact.emp <- varimax(unrot.fact.emp)
#View(unrot.fact.emp)
rot.fact.emp
```


```{r}
# The print method of varimax omits loadings less than abs(0.1). In order to display all the loadings, it is necessary to ask explicitly the contents of the object $loadings
fact.load.emp <- rot.fact.emp$loadings[1:9,1:4]
fact.load.emp
```

```{r}
# Computing the rotated factor scores, Notice that signs are reversed for factors F2 (PC2), F3 (PC3) and F4 (PC4)
scale.emp <- scale(ship)
scale.emp

```





