---
title: "Mean and Variance Analaysis"
author: "Deviprasad Saka"
date: "2024-02-25"
output: html_document
---
```{r}
# Provide the file path to CSV file
file_path <- "D:/Multivariate Analysis/Assignment-1/train US new.csv"

# Import the CSV file into R
data <- read.csv(file_path)

# View the imported data
#print(data)
```


```{r}
#Analyzing the univariate mean and variance of the “Air Quality index” variable
library(ggplot2)

# Calculate mean and variance for Air Quality Index
mean_AQI <- mean(data$Air_Quality_Index)
variance_AQI <- var(data$Air_Quality_Index)

print(paste("Mean for Total AQI:", mean_AQI))
## [1] "Mean for Total AQI: 38.036"
print(paste("Variance for Total AQI:", variance_AQI))
## [1] "Variance for Total AQI: 1317.737"
```

```{r}
# Box Plot for Air Quality Index
ggplot(data, aes(x = "", y = Air_Quality_Index)) +
  geom_boxplot(fill = "skyblue", color = "black") +
  labs(title = "Box Plot of Air Quality Index", x = "", y = "Air Quality Index")
```

```{r}
# Q-Q plot for Air Quality Index
qqnorm(data$Air_Quality_Index, main = "Q-Q Plot of Air Quality Index", col = "blue")  # Adding color
qqline(data$Air_Quality_Index)
```

